config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'bikes#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'pages#dashboard'
  patch "rentals/:id/accept_booking", to: "rentals#mark_as_accepted", as: :accepted
  patch "rentals/:id/reject_booking", to: "rentals#mark_as_rejected", as: :rejected

  resources :users, only: [ :destroy, :update ]
  resources :bikes do
    resources :rentals, only: [ :new, :create ]
    #in case we want to add reviews
    #resources :reviews, only: [ :new, :create ]
  end
  resources :rentals, only: [ :show, :update, :index, :create ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :rentals, dependent: :destroy

  def image(classname = nil, height = 255, width = 255)
    if photo.attached?
      cl_image_tag photo.key, height: height, width: width, crop: :fill, class: classname
    else
      url = "https://source.unsplash.com/#{width}x#{height}/?#{bike_type.gsub(/\s/, ',')},bicycle"
      "<img src='#{url}' alt='bike' class='#{classname}' width='#{width}' height='#{height}'>"
    end
  end

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :bike

  def accept!
    self.booking_confirmed = true
  end

  def reject!
    self.booking_confirmed = false
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bikes, dependent: :destroy
  has_many :rentals, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :user_location

  def index
    if params[:query].present?
      @bikes = Bike.where("(lower(bike_type) LIKE '%#{params[:query].downcase}%')
                        OR (lower(brand) LIKE '%#{params[:query].downcase}%')
                        OR (year = #{params[:query].to_i})")
      @query = params[:query]
    else
      @bikes = Bike.all
    end
  end

  def show
    @bike = Bike.find(params[:id])
    @bikes = Bike.all
    @rental = Rental.new
    @marker = { lat: @bike.latitude, lng: @bike.longitude }
  end

  def new
    @bike = Bike.new
    @marker = { lat: @user_location[0], lng: @user_location[1] }
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    if @bike.save
      redirect_to bike_path(@bike)
    else
      render :new
    end
  end

  private

  def user_location
    if request.key?('HTTP_HOST')
      if request['HTTP_HOST'].nil? || request['HTTP_HOST'].include?("localhost")
        @user_location = [45.525990, -73.595410]
      end
    else
      @user_location = [request.location.longitude, request.location.latitude]
    end
  end

  def bike_params
    params.require(:bike).permit(:frame_size, :seat_count, :bike_type, :year, :brand, :price, :location, :available_for_rent, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @user = current_user
    @my_bikes = Bike.where(user: current_user)
    @bikes_i_rent = Bike.joins(:rentals).where(rentals: { user_id: current_user.id })
    @my_rentals = Rental.where(user: current_user)
    @rental_request_received = Rental.joins(:bike).where(bikes: { user_id: current_user.id })
  end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def index
    @rentals = Rental.all
  end

  def show
    @rental = Rental.find(@rental)
  end

  def create
    @bikes = Bike.all
    @bike = Bike.find(params[:bike_id])

    @rental = Rental.create(rental_params)
    @rental.bike = @bike
    @rental.user = current_user

    if @rental.save
      redirect_to dashboard_path
    else
      render "bikes/show"
    end
  end

  def mark_as_accepted
    @rental = Rental.find(params[:id])
    @rental.accept!
    @rental.save
    redirect_to dashboard_path
  end

  def mark_as_rejected
    @rental = Rental.find(params[:id])
    @rental.reject!
    @rental.save
    redirect_to dashboard_path
  end

private

  def rental_params
    params.require(:rental).permit(:rental_start, :rental_end, :message, :booking_confirmed)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authenticate_user!, only: :home

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/index.html.erb
<div class="container mt-3">

  <h1><%= @query.nil? ? "All bikes:" : "Bikes matching '#{@query}'" %></h1>

  <%= render 'shared/searchbar' unless request.env['PATH_INFO'] == "/" %>

  <%= render 'shared/bikesgrid' %>

</div>

app/views/bikes/new.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
   <div class="col-sm-12 col-md-6">
    <div class="card p-2">
      <div class="m-3">
        <%= simple_form_for(@bike) do |f|  %>
          <%= f.input :location, id: "bike_location" %>

          <%= f.input :brand %>

          <%= f.input :bike_type %>

          <%= f.input :frame_size %>

          <%= f.input :year %>

          <%= f.input :price %>

          <%= f.input :available_for_rent, :as => :hidden, :input_html => { :value => true } %>

          <%= f.input :photo, as: :file %>
          <%= f.submit "Post Bike", class: "btn btn-primary" %>
        <% end  %>
      </div>
    </div>
  </div>

  <!-- map -->
   <div class="col-sm-12 col-md-6">
     <div id="map"
     style="width: 100%; height: 400px;"
     data-markers="<%= @marker.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
   </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/places.js@1.19.0"></script>
<script>
  const apiKey = '3058c1596485038bb45e505a4f9b4f03';
  let bike_loc = document.querySelector('#bike_location');
  let map = document.querySelector('#map');
  let url = `http://api.openweathermap.org/data/2.5/weather?&appid=${apiKey}&units=metric&q=${bike_loc.value}`;

  var placesAutocomplete = places({
    container: bike_loc
  });

  const drawMap = (lon, lat) => {
    mapboxgl.accessToken = token;
    const map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/light-v10', // stylesheet location
      center: [lon, lat], // starting position [lng, lat]
      zoom: 9 // starting zoom
    });
    new mapboxgl.Marker()
      .setLngLat([lon, lat])
      .addTo(map);
  };

  const callAPI = (url) => {
  fetch(url)
    .then(response => response.json())
    .then((data) => {
      lon = data['features'][0]['center'][0];
      lat = data['features'][0]['center'][0];
      drapMap(lat, lon)
      console.log(markers)
    });
  };

  bike_loc.addEventListener('blur', (e) => {
    callAPI(`https://api.mapbox.com/geocoding/v5/mapbox.places/${bike_loc.value}.json?access_token=pk.eyJ1IjoieWVzc2hlY29kZSIsImEiOiJja2UzOHRicmUwNHYzMnJwcTl1YjBvdW15In0.4SgLEVv2ZyMHtfCcxYJhGQ`);
  });

</script>

app/views/bikes/show.html.erb
   <div class="container mt-3">
     <div class="row justify-content-center">
      <!-- bike details and form -->

       <div class="col-sm-12 col-md-6">
        <div class="card p-2">
          <div class="card-details">
            <div class="align-center mt-3 ml-3">
              <%= raw @bike.image %>
            </div>
            <div class="px-3 mt-3">
              <h2 class="card-title">
              <%= @bike.brand %>
              <%= @bike.bike_type %>
              <small>(<%= @bike.year %>)</small>
              </h2>

              <div>
              <i class="fas fa-map-marker-alt red"></i> <%= @bike.location %><br>
              <i class="fas fa-arrows-alt-v"></i> <%= @bike.frame_size %>cm frame size<br>
              <br>
                <strong class="blue">$<%= @bike.price %>/hr</strong>
              </div>
            </div>
          </div>
          <div class="m-3">
            <!--  using flatpickr for this
                  config in application.js / application.css -->
            <%= simple_form_for [ @bike, @rental ] do |f| %>
              <%= f.input :rental_start,
                  as: :string %>
              <%= f.input :rental_end,
                  as: :string %>
              <%= f.input :message %>
              <%= f.button :submit, class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>


      <!-- map -->
       <div class="col-sm-12 col-md-6">
         <div id="map"
         style="width: 100%; height: 400px;"
         data-markers="<%= @marker.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
       </div>
      </div>
   </div>

    <!-- see more bikes -->
    <div class="container">
    <h2 class="mb-4 mt-4 ml-4">Other bikes near you</h2>

    <%= render 'shared/bikesgrid' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freewheel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <header>
      <%= render 'shared/flashes' %>
      <%= render 'shared/navbar' %>
    </header>

    <% if request.env['PATH_INFO'] == "/" %>
    <div class="banner" style="
      padding: 125px 0; 
      background-image: 
        linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), 
        url(https://source.unsplash.com/nPOtzvGLYW0/1600x900); 
      background-position: bottom">
      <div class="container">
        <h1>Bixi is <strong>boring</strong>! Rent with style by the hour or day!</h1>
        <p>Search for cool bikes near you</p>
        <%= render 'shared/searchbar' %>
      </div>
    </div>
    <% end %>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">

    <!-- user info card -->

    <div class="col-12 col-md-4 mt-4 mb-4">
      <div class="card-profile">
        <div class="card-profile-details">
          <% if current_user.first_name == "Ryan" %>
            <img src="https://kitt.lewagon.com/placeholder/users/ryanbuckleyca"/>
          <% else %>
            <img src="https://kitt.lewagon.com/placeholder/users/mynameisnirali"/>
          <% end %>

          <div class="card-profile-infos">
            <h2><%= @user.first_name %> <%= @user.last_name %></h2>
            <p><%= @user.email %></p>
            <p><%= @user.phone_number %></p>
            <div class="card-profile-actions">
              <a href="#">Edit my profile</a><br />
              <a href="#">Delete my account</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- BOOKINGS ----------------->
    <div class="col-12 col-md-8 mt-4 mb-4">

    <h3> Bikes I own:</h3>
    <span>
      <% @my_bikes.each do |bike| %>
      <div class="card mb-2 p-0">
        <div class="card-profile-details m-3 align-items-start" style="display:flex !important">
          <div class="align-left">
            <%= raw bike.image %>
          </div>
          <div class="px-3 w-100">
            <h2 class="card-title">
              <%= bike.brand %> <%= bike.bike_type %> <small>(<%= bike.year %>)</small>
            </h2>
            <div>
              <i class="fas fa-map-marker-alt red"></i> <%= bike.location %><br>
              <i class="fas fa-arrows-alt-v"></i> <%= bike.frame_size %>cm frame<br>
              <div class="d-flex justify-content-between">
                <strong class="blue">$<%= bike.price %>/hr</strong>
                <div>
                  <i class="fas fa-edit blue"></i>
                  <i class="far fa-trash-alt red"></i>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </span>
    <hr>

    <h3> Bikes I rent from others:</h3>
      <span>
        <% @my_rentals.each do |rental|%>
          <%= render partial: 'shared/rentalcard', locals: { rental: rental } %>
        <% end %>
      </span>
    <hr>

    <h3> Bikes others rent from me:</h3>
      <div>
        <% @rental_request_received.each do |rental|%>
          <%= render partial: 'shared/rentalcard', locals: { rental: rental } %>
        <% end %>
      </div>

    </div>
  </div>

app/views/rentals/index.html.erb
<h1>All Rentals</h1>
<% @rentals.each do |rental| %>
  <h2>Rental #<%= rental.id %></h2>
  <ul>
    <li>User #<%= rental.user.id %>:
      <ul>
        <li><%= rental.user.first_name %></li>
        <li><%= rental.user.last_name %></li>
        <li><%= rental.user.phone_number %></li>
        <li><%= rental.user.email %></li>
      </ul>
    </li>
    <li>Bike #<%= rental.bike.id %>:
      <ul>
        <li>frame_size: <%= rental.bike.frame_size %></li>
        <li>seat_count: <%= rental.bike.seat_count %></li>
        <li>bike_type: <%= rental.bike.bike_type %></li>
        <li>year: <%= rental.bike.year %></li>
        <li>brand: <%= rental.bike.brand %></li>
        <li>price: <%= rental.bike.price %></li>
        <li>location: <%= rental.bike.location %></li>
        <li>available_for_rent: <%= rental.bike.available_for_rent %></li>
      </ul>
    </li>
    <li>rental_start: <%= rental.rental_start %></li>
    <li>rental_end: <%= rental.rental_end %></li>
    <li>booking_confirmed: <%= rental.booking_confirmed %></li>
    <li>bike_returned: <%= rental.bike_returned %></li>
    <li>message: <%= rental.message %></li>
  </ul>
<% end %>

app/views/shared/_bikesgrid.html.erb
<div class="row">
  <% @bikes.each do |bike| %>
    <div class="card-group col-lg-3 col-md-4 col-sm-6 offset-sm-0 col-10 offset-1">
      <%= link_to bike_path(bike), class: "card my-3" do %>
        <%= raw bike.image('card-img-top') %>
        <div class="card-body">
          <h2 class="card-title">
          <%= bike.brand %>
          <%= bike.bike_type  %>
          <small>(<%= bike.year %>)</small>
          </h2>
          <p class="card-text">
           <i class="fas fa-map-marker-alt red"></i> <%= bike.location %>
          </p>
        </div>
        <div class="card-footer d-flex justify-content-between">
          <% if [@user_location, bike.latitude, bike.longitude].all? %>
            <%= Geocoder::Calculations.
            distance_between(@user_location, [bike.latitude, bike.longitude]).floor %>km away!
          <% else %>
            Unknown gps
          <% end %>
          <strong class="blue">$<%= bike.price %>/hr</strong>
        </div>
      <% end %>
    </div>
  <% end  %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo.png" %><h1>freewheel</h1>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add a bike", new_bike_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Rent a bike", bikes_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.first_name == "Ryan" %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ryanbuckleyca", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/mynameisnirali", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Logout", "#", class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_rentalcard.html.erb
<div class="card mb-2 p-0">
  <div class="card-details m-3">
    <div class="align-center">
      <%= raw rental.bike.image %>
    </div>
    <!-- booking-details -->
    <div class="px-3">
      <h2 class="card-title">
      <%= rental.bike.brand %> <%= rental.bike.bike_type %> <small>(<%= rental.bike.year %>)</small>
      </h2>
      <!-- time and price row -->
      <div class="d-flex align-items-center">
        <div>
          <%= rental.rental_start.strftime("%m/%d/%y") %><br>
          <%= rental.rental_start.strftime("%I:%M%p") %>
        </div>
        <i class="fas fa-angle-double-right blue p-2" style="font-size: 36px"></i>
        <div>
          <%= rental.rental_end.strftime("%m/%d/%y") %><br>
          <%= rental.rental_end.strftime("%I:%M%p") %>
        </div>
        <i class="fas fa-equals blue p-3" style="font-size: 24px"></i>
        <strong class="blue text-center">
          <% hours = (rental.rental_end - rental.rental_start) / 3600 %>
          $<%= rental.bike.price * hours.floor %> total
        </strong>
      </div>
    </div>
  </div>
  <!-- booking-confirmation -->
  <% if rental.user != current_user %>
    <% if rental.booking_confirmed %>
      <p class="alert-success m-0 p-3">
        booking confirmed!
      </p>
    <% else %>
    <div class="p-3">
      <p><%= rental.message %></p>
      <%= link_to "Accept", accepted_path(rental), method: :patch, class: 'btn blue blue-btn', data: { confirm: "Confirm this request?" } %>
      <%= link_to "Reject", rejected_path(rental), method: :patch, class: 'btn red red-btn', data: { disable_with: "Please wait..." } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_searchbar.html.erb
<div class="input-group md-form form-sm form-2 pl-0">
<%= form_tag bikes_path, method: :get, class: 'form-inline w-100' do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control my-0 py-1 flex-grow-1",
    placeholder: 'Search bikes'
  %>
  <div class="input-group-append">
    <%= button_tag(type: "submit", class: "input-group-text lighten-3 h-auto") do %>
    <i class="fas fa-search text-white" aria-hidden="true"></i>
    <% end %>
    </span>
  </div>
<% end %>
</div>

app/views/users/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>